project:
  type: book
  output-dir: _book

book:
  title: "L // WLM 2023"
  subtitle: "Конспекты лекций"
  author:
    - name: "Антон Ангельгардт"
      email: "anton.angelgardt@gmail.com"
      affiliations:
        - name: "HSE UX LAB, HSE University"
  date: last-modified
  date-format: "MMM D, YYYY"
  chapters:
    - index.qmd
    - part: part-r.qmd
    - l1.qmd
    - l2.qmd
    - part: part-math.qmd
    - l3.qmd
    - l4.qmd
    - l5.qmd
    - l6.qmd
    - part: part-andan.qmd
    - l7.qmd
    - l8.qmd
    - l9.qmd
    - l10.qmd
    - l11.qmd
    - l12.qmd
    - l13.qmd
    - l14.qmd
    - l15.qmd
    - references.qmd
  favicon: pics/favicon.png
  navbar: 
    title: "WLM 2023 // HSE UX LAB"
    logo: pics/logo.png
    left: 
      - text: "Книга"
        href: ../book/index.html
      - text: "Лекции"
        href: ../lectures/index.html
      - text: "Практики"
        href: ../practice/index.html
      - text: "Домашки"
        href: ../homeworks/index.html
      - text: "Проекты"
        href: ../projects/index.html
    collapse: true
    background: gray-700

bibliography: references.bib

comments:
  hypothesis: true

format:
  html:
    cover-image: pics/lec-cover.png
    theme: 
      light: [css/lightstyle.scss]
      dark: [css/darkstyle.scss]
  pdf:
    documentclass: scrreprt

editor: source

