project:
  type: book

book:
  title: "HW // WLM 2023"
  subtitle: "Домашки"
  author:
    - name: "Антон Ангельгардт"
      email: "anton.angelgardt@gmail.com"
      affiliations:
        - name: "HSE UX LAB, HSE University"
  date: last-modified
  date-format: "MMM D, YYYY"
  chapters:
    - index.qmd
    - hw1.qmd
    - hw2.qmd
    - hw3.qmd
    - hw4.qmd
    - hw5.qmd
    - hw6.qmd
    - hw7.qmd
    - hw8.qmd
    - hw9.qmd
    - hw10.qmd
    - hw11.qmd
    - hw12.qmd
    - hw13.qmd
    - hw14.qmd
    - hw15.qmd
    - hw16.qmd
    - references.qmd
  favicon: pics/favicon.png
  navbar: 
    title: "WLM 2023 // HSE UX LAB"
    logo: pics/logo.png
    left: 
      - text: "Книга"
        href: ../book/index.html
      - text: "Лекции"
        href: ../lectures/index.html
      - text: "Практики"
        href: ../practice/index.html
      - text: "Домашки"
        href: ../homeworks/index.html
      - text: "Проекты"
        href: ../projects/index.html
    collapse: true
    background: gray-700


bibliography: references.bib

format:
  html:
    callout-appearance: simple
    cover-image: pics/hw-cover.png
    theme: 
      light: [css/lightstyle.scss, css/style.scss]
      dark: [css/darkstyle.scss, css/style.scss]
  pdf:
    documentclass: scrreprt

editor: source

