project:
  type: book

book:
  title: "WLM 2023"
  subtitle: "Анализ данных и машинное обучение для исследователей"
  author:
    - name: "Антон Ангельгардт"
      email: "anton.angelgardt@gmail.com"
      affiliations:
        - name: "HSE UX LAB, HSE University"
  date: last-modified
  date-format: "MMM D, YYYY"
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - signs.qmd
    - part: part-r.qmd
    - r-basics.qmd
    - r-dtypes.qmd
    - r-dstructs.qmd
    - r-funcs.qmd
    - r-controlflow.qmd
    - r-data.qmd
    - r-strings.qmd
    - r-dates.qmd
    - r-vis.qmd
    - r-tidy.qmd
    - r-ggplot2.qmd
    - part: part-py.qmd
    - part: part-math.qmd
    - math-logic.qmd
    - math-settheory.qmd
    - math-combinatorics.qmd
    - math-analysis.qmd
    - math-linal.qmd
    - part: part-measurements.qmd
    - measurements-social-sci.qmd
    - measurements-psychomentrics.qmd
    - part: part-stats.qmd
    - stats-intro.qmd
    - stats-rand-exp.qmd
    - stats-rand-values.qmd
    - stats-estim.qmd
    - stats-testing.qmd
    - part: part-andan.qmd
    - andan-descriptives.qmd
    - andan-ttest.qmd
    - andan-chisq.qmd
    - andan-corr.qmd
    - andan-nonparam.qmd
    - andan-simplelinear.qmd
    - andan-multiplelinear.qmd
    - andan-polynomial.qmd
    - andan-svr.qmd
    - andan-regreg.qmd
    - andan-anova.qmd
    - andan-ancova.qmd
    - andan-manova.qmd
    - andan-treesreg.qmd
    - andan-randforestreg.qmd
    - andan-distributions.qmd
    - andan-logreg.qmd
    - andan-multinomlogreg.qmd
    - andan-poissonreg.qmd
    - andan-glmm.qmd
    - andan-gam.qmd
    - andan-svm.qmd
    - andan-treesclass.qmd
    - andan-randforestclass.qmd
    - andan-cluster.qmd
    - andan-lda.qmd
    - andan-pca.qmd
    - andan-ica.qmd
    - andan-cca.qmd
    - andan-efa.qmd
    - andan-sem.qmd
    - andan-cfa.qmd
    - andan-path.qmd
    - andan-timeseries.qmd
    - part: part-randan.qmd
    - randan-descriptives.qmd
    - randan-ttest.qmd
    - randan-chisq.qmd
    - randan-corr.qmd
    - randan-nonparam.qmd
    - randan-simplelinear.qmd
    - randan-multiplelinear.qmd
    - randan-polynomial.qmd
    - randan-svr.qmd
    - randan-regreg.qmd
    - randan-anova.qmd
    - randan-ancova.qmd
    - randan-manova.qmd
    - randan-treesreg.qmd
    - randan-randforestreg.qmd
    - randan-distributions.qmd
    - randan-logreg.qmd
    - randan-multinomlogreg.qmd
    - randan-poissonreg.qmd
    - randan-glmm.qmd
    - randan-gam.qmd
    - andan-svm.qmd
    - randan-treesclass.qmd
    - randan-randforestclass.qmd
    - randan-cluster.qmd
    - randan-lda.qmd
    - randan-pca.qmd
    - randan-ica.qmd
    - randan-cca.qmd
    - randan-efa.qmd
    - randan-sem.qmd
    - randan-cfa.qmd
    - randan-path.qmd
    - randan-timeseries.qmd
    - part: part-pyandan.qmd
    - part: part-appendices.qmd
    - appendix-numbers.qmd
    - appendix-strings.qmd
    - appendix-kilobytes.qmd
    - appendix-memory.qmd
    - appendix-proglang.qmd
    - appendix-git.qmd
    - appendix-formulas.qmd
    - references.qmd
  favicon: pics/favicon.png
  navbar: 
    title: "WLM 2023 // HSE UX LAB"
    logo: pics/logo.png
    left:
      - text: "Домой"
        href: ../hub/index.html
      - text: "Книга"
        href: ../book/index.html
      - text: "Лекции"
        href: ../lectures/index.html
      - text: "Практики"
        href: ../practice/index.html
      - text: "Домашки"
        href: ../homeworks/index.html
      - text: "Проекты"
        href: ../projects/index.html
    collapse: true
    background: gray-700

bibliography: references.bib

format:
  html:
    cover-image: pics/book-cover.png
    theme: 
      light: [lightstyle.scss, custom.scss, tasklight.scss]
      dark: [darkstyle.scss, custom.scss, taskdark.scss]
  pdf:
    documentclass: scrreprt

highlight-style: github

editor: source
